### ISSUE TITLE
Als record manager wil ik dat er een verklaring van vernietiging (of proces verbaal) wordt gegenereerd over de vernietiging van documenten

### ISSUE THREAD

**Issue by JurjenBert** [maykinmedia/archiefvernietigingscomponent#55]
zodat ik kan voldoen aan de archiefwet. De verklaring van vernietiging (of proces verbaal) is het bewijs van daadwerkelijke vernietiging. Hierin is opgenomen: een specificatie van het vernietigde (de vernietigingslijst), op grond waarvan vernietigd is (de selectiecategorie) en de wijze waarop vernietigd is (een beschrijving hoe technisch is vernietigd; hierbij is het van belang duidelijk te maken hoe ervoor is gezorgd dat onherstelbaar is vernietigd).   
graag oppakken met #62 

[Thema uit conceptofferte: 2. Proces-verbaal/rapport genereren van vernietiging] 

--

*Clearification*

There should be like a template document with a table as attachment. This template document should be configuratble. Columns for the attachment are:

![image](https://user-images.githubusercontent.com/96970/105352477-3be2de80-5bee-11eb-9f82-c805cec92550.png)

* SAD should be gemeentearchivaris.

*Guestimate*

* Uniek kenmerk = Zaak.identificatie
* Beschrijving = Zaak.omschrijving
* Looptijd = Zaak.Einddatum - Zaak.Startdatum
* VCS = Zaak.Zaaktype.Selectielijstprocestype.Nummer
* Toelichting = App.DestructionList.toelichting
* Opmerkingen = App.DestructionList.comments
* Reactie zorgdrager = Comment from process owner

**Comment by SilviaAmAm** [comment]
Is it enough to send the report via email once the destruction list has been removed? Or should it be visible also from the app?

**Comment by joeribekker** [comment]
Mirjam indicated the description should be removed, and zaaktype and destruction date should be added.

**Comment by SilviaAmAm** [comment]
Additional comment after meeting:
The columns `Opmerkingen` and `Reactie Zorgdrager` contain comments. In the current implementation we use the last comment from each in the report. This is because when the archivist/process owner require changes, after the changes are made the review process restarts from the beginning. So it was decided that it is unnecessary to see all the comments that have lead to changes (since the final report contains only the final destruction list).

If all the comments that have been made throughout the review process should be included in the report, a new user story should be made.

**Comment by SilviaAmAm** [comment]
After discussion:

The columns to be shown in the report that the process owner can see in the app are:

1. Uniek kenmerk
2. Beschrijving (optional, configured by the record manager when creating the list)
3. Loop tijd
4. VCS
5. Toelichting
6. Opmerkingen (optional, configured by the record manager when creating the list)
7. Reactie Zorgdrager
8. Zaaktype
9. Bewaartermijn
10. Resultaattype
11. Verantwoordelijke organisatie
12. Relaties
